# Generated by Django 5.2.1 on 2026-05-26 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='Dinner', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='mealplan',
            unique_together={('user', 'recipe', 'meal_type')},
        ),
    ]
